name: crawllet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: any
  cupertino_icons: ^1.0.2
  firebase_auth: any
  firebase_core: any
  flutter:
    sdk: flutter
  flutter_color: ^2.0.0
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  local_auth: ^2.1.0
  objectbox: ^1.6.0
  objectbox_flutter_libs: any

dev_dependencies:
  build_runner: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.5
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/main.png"
  adaptive_icon_background: "#BF4040"

flutter_native_splash:
  color: "#545775"
  image: assets/icons/main.png
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/gifs/

  fonts:
    - family: myanamarText
      fonts:
        - asset: assets/fonts/myanamarText.ttf
        - asset: assets/fonts/myanamarTextBold.ttf
          weight: 900
    - family: rockwell
      fonts:
        - asset: assets/fonts/rockwellRegular.ttf
    - family: harlow
      fonts:
        - asset: assets/fonts/harlowSolidRegular.ttf
